### ISSUE TITLE
Erreur sur "npm install"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-community-contributions#10]
```
$ npm install
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thbar/.npm/_logs/2021-01-07T18_30_57_962Z-debug.log
```

Mon setup (asdf) respecte `.tool-versions` et est donc actuellement (voir #9) sur les versions suivantes (je crois que c'est lié à la version de npm):

```
$ npm --version
6.4.1
$ node --version
v10.14.2
```

**Comment by thbar** [comment]
Je passe à des versions plus récentes ([dernière LTS](https://nodejs.org/en/)):

```
$ npm --version
6.14.10
$ node --version
v14.15.4
```

Cela se passe mieux mais j'ai une grosse erreur (multiples lignes) `Error: Cannot find module 'nan'`.

Je détermine que si je l'ajoute à la main ça corrige le souci (`npm install nan`).

**Comment by thbar** [comment]
En résumé je pense qu'il faut mettre à jour Node et ajouter une dépendance manquante, après quoi j'arrive à lancer les tests avec succès.

**Comment by antoine-de** [comment]
étrange, j'ai pas eu de soucis moi 🤔

**Comment by thbar** [comment]
J'ai trouvé a priori !
- les "aliases" ont été ajoutés dans npm 6.9.0 (https://npm.community/t/release-npm-6-9-0/5911)
- le `.tool-versions` fixe node à 10.14.2, le plugin `asdf-nodejs` que j'ai en place le lit et installe cette version, qui vient avec node 6.4.1

@antoine-de si tu peux partager ton `node --version` et `npm --version` je pense que ça permettra de vérifier ça.

Bref en mettant à jour ça supprimera tout problème.

**Comment by thbar** [comment]
(pardon il fallait lire npm 6.4.1 et non node 6.4.1)

**Comment by AntoineAugusti** [comment]
@fchabouis Résolu dans #27 ?
