### ISSUE TITLE
Les nouveaux lieux de covoiturage n'apparaissent plus systématiquement sur la carte en orange

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-community-contributions#18]
Dans l'outil Contribuer, lorsqu'on ajoute de nouveaux lieux de covoiturage, on peut les visualiser sur une carte grâce à l'option "🗺️ Voir la carte". Les nouveaux points apparaissent en orange (les autres lieux de covoiturage de la BNLC sont en bleu).
Depuis le mois de décembre 2021, les points n'apparaissent pas en orange à chaque ajout.

Il y a un nombre de points à partir duquel ça apparaît sur la carte ?

**Comment by fchabouis** [comment]
J'ai l'impression que ça fonctionne là, donc je cloture
![image](https://user-images.githubusercontent.com/15341118/234823984-08fbf662-6013-42fe-88f4-aed122146705.png)
