### ISSUE TITLE
Erreur (sans message) si mauvais encodage fichier

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-community-contributions#34]
Lorsqu'un utilisateur charge un fichier CSV avec un mauvais encodage (dans le cas rencontré, encodage ISO-8859-1 au lieu de UTF-8), l'utilisateur ne voit aucun message d'erreur et ne peut pas passer à l'étape suivante. Il y a cependant un message dans la console du navigateur. (fichier *export_covoit_eure.csv*)
[export_covoit_eure.csv](https://github.com/etalab/transport-base-nationale-covoiturage/files/11937299/export_covoit_eure.csv)
![image](https://github.com/etalab/transport-base-nationale-covoiturage/assets/4528670/62e40adf-0fee-4028-bf85-7f5e18baa070)

Si le fichier est converti en UTF-8, l'outil fonctionne correctement. (fichier : *export_covoit_eure_utf8.csv*)
[export_covoit_eure_utf8.csv](https://github.com/etalab/transport-base-nationale-covoiturage/files/11937300/export_covoit_eure_utf8.csv)
![image](https://github.com/etalab/transport-base-nationale-covoiturage/assets/4528670/26705ce1-7219-4861-b4bd-8afe52858eba)

Le validateur schema.data.gouv.fr arrive, quant à lui, à lire le fichier encodé en ISO-8859-1.
![image](https://github.com/etalab/transport-base-nationale-covoiturage/assets/4528670/b2daec4b-89d3-496a-aace-92fbfd7e08f1)

**Comment by AntoineAugusti** [comment]
@AurelienC Normalement un ancien commit gérait ce cas https://github.com/etalab/transport-community-contributions/commit/eed4ca3c9520e09c3a264b0676abc10d256aecb1 😢 

Tu peux partager un fichier avec un encoding != UTF-8 ?

**Comment by AntoineAugusti** [comment]
@AurelienC Penses-tu que l'on doive accepter des contributions où l'encodage n'est pas UTF-8 ? Ça pourrait poser des problèmes

**Comment by AurelienC** [comment]
@AntoineAugusti Cela me semble correct de n'accepter que l'encodage UTF-8 et d'éviter d'avoir une BNLC une fois en UTF-8, une fois en ISO-8859-1, etc.

**Comment by AurelienC** [comment]
Un autre fichier provoque la même erreur dans l'outil Contribuer. Il semble bien au format UTF-8, mais l'outil schema.data.gouv.fr affiche une erreur lors de la lecture en UTF-8.
![image](https://github.com/etalab/transport-community-contributions/assets/4528670/88d79669-fefc-462f-aefd-adbbf0af8ea7)


Si le fichier est ouvert en UTF-8, non modifié et enregistré en UTF-8 avec LibreOffice Calc, cette fois-ci, plus d'erreurs. Je suis en attente du logiciel utilisé par le contributeur.

Serait-il possible d'ajouter une sorte de try/catch qui englobe l'ensemble pour afficher une erreur à l'utilisateur systématiquement @AntoineAugusti  ?

Le fichier BNLC.csv
[BNLC.csv](https://github.com/etalab/transport-community-contributions/files/11965934/BNLC.csv)

**Comment by AntoineAugusti** [comment]
@AurelienC Ça te conviendrait ? 
![image](https://github.com/etalab/transport-community-contributions/assets/295709/c9456afa-564d-475e-8efc-b22edd75d585)

**Comment by AurelienC** [comment]
Oui, très bien, merci @AntoineAugusti  !

**Comment by thbar** [comment]
@AurelienC @AntoineAugusti c'est en cours de déploiement !
