### ISSUE TITLE
Erreur lors de l'envoi d'un fichier au moment de la création de la pull request

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-community-contributions#39]
Lors de l'envoi d'un fichier (testé avec deux fichiers différents), une erreur arrive lors de l'envoi du fichier, après sa validation.

<img width="749" alt="image" src="https://github.com/etalab/transport-community-contributions/assets/4528670/311ac0de-c667-4e90-ac66-4cad7eb98457">

<img width="1254" alt="image" src="https://github.com/etalab/transport-community-contributions/assets/4528670/da5fde7c-6301-4564-9bf0-16e2747280d7">

<img width="655" alt="image" src="https://github.com/etalab/transport-community-contributions/assets/4528670/643ce851-94b0-4794-af98-c99efb9b331b">

**Comment by AurelienC** [comment]
<img width="722" alt="image" src="https://github.com/etalab/transport-community-contributions/assets/4528670/0168d815-aced-4cf3-8d7b-5d988c583cb7">


Est-ce que l'erreur eut venir de ça ? https://github.com/the-nice-bot/transport-base-nationale-covoiturage/pull/108

**Comment by AntoineAugusti** [comment]
Je viens de regarder, voici ce que j'en comprends.

Le code concerné est ici

https://github.com/etalab/transport-community-contributions/blob/9d3350e0bdaee35d8ca73bf2371ebe63a088ba7e/src/utils/anonymousPR.js#L45-L78

J'imagine :
- que la PR pour mettre à jour le fork a été créée dans le passé
- cette PR n'a pas pu être mergée à un moment (erreur temporaire de GitHub ?)
- le try/catch ne gère pas ce cas (la PR existe mais n'a pas été mergée)

L'action que j'ai effectuée est de merger https://github.com/the-nice-bot/transport-base-nationale-covoiturage/pull/108 avec l'API GitHub en utilisant un token de `the-nice-bot` (il faut changer l'adresse d'e-mail pour ne pas être bloqué par le 2FA, je suis en train de voir avec @fchabouis).

Je pense que ceci est extrêmement rare, peut-être que c'est OK de ne pas modifier le code !

**Comment by AurelienC** [comment]
OK, ça a dû résoudre ce problème exceptionnel, j'ai pu envoyer un fichier correctement. Merci @AntoineAugusti !
